name: Backup Firestore

on:
  schedule:
    - cron: '0 0 * * *'

env:
  PROJECT_ID: visible-thoughts-writer
  BUCKET: gs://visible-thoughts-writer-firestore-backup

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/setup-gcloud@main
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
          version: '2.298.2'
      - run: gcloud info
      - run: gcloud config set project $PROJECT_ID
      - run: gcloud firestore export $BUCKET
