name: Backup Firestore

on:
  push:
    paths:
      - '.github/workflows/backup.yml'

env:
  PROJECT_ID: visible-thoughts-writer
  BUCKET: gs://visible-thoughts-writer-firestore-backup

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
      - uses: google-github-actions/setup-gcloud@v1
      - run: gcloud info
      - run: gcloud config set project $PROJECT_ID
      - run: gcloud firestore export $BUCKET
